create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  chat_id bigint not null,
  role text not null check (role in ('user', 'assistant', 'system')),
  content text not null,
  created_at timestamp with time zone not null default now()
);

create index if not exists messages_chat_id_created_at_idx
  on public.messages (chat_id, created_at desc);
